apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-1q8p
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0053-tenant/tkrw-pr712-0075-0053-app/devfile-sample-1q8p@sha256:fbe166af0dae94ba181787372ba966e6d391cb630e6f86fbd28e8ba3c946fd39
        name: my-nodejs
        resources: {}
status: {}
